# Generated by Django 5.0.1 on 2024-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_orderitem_image_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/sample.png", null=True, upload_to=""
            ),
        ),
    ]
